# K-Means Example

Implement K-Means algorithm with TensorFlow, and apply it to classify
handwritten digit images. 

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.contrib.factorization import KMeans

In [2]:
# Import MNIST data
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)
full_data_x = mnist.train.images

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [12]:
# Parameters
num_steps = 50     # Total steps to train
batch_size = 1024  # The number of samples per batch
k = 25             # The number of clusters
num_classes = 10   # The 10 digits
num_features = 784 # Each image is 28x28 pixels

# Input images
X = tf.placeholder(tf.float32, shape=[None, num_features])
# Labels (for assigning a label to a centroid and testing)
Y = tf.placeholder(tf.float32, shape=[None, num_classes])

# K-Means Parameters
kmeans = KMeans(inputs=X, num_clusters=k, distance_metric='cosine',
                use_mini_batch=True)

In [13]:
# Build KMeans graph
(all_scores, cluster_idx, scores, cluster_centers_initialized,\
 cluster_centers_var, init_op, train_op) = kmeans.training_graph()

cluster_idx = cluster_idx[0] # fix for cluster_idx being a tuple
avg_distance = tf.reduce_mean(scores)

# Initialize the variables (i.e. assign their default value)
init_vars = tf.global_variables_initializer()

In [10]:
# Start TensorFlow session
sess = tf.Session()

# Run the initializer
sess.run(init_vars, feed_dict={X: full_data_x}) # init tf
sess.run(init_op, feed_dict={X: full_data_x})   # init kmeans

# Training
for i in range(1, num_steps + 1):
    _, d, idx = sess.run([train_op, avg_distance, cluster_idx],
                         feed_dict={X: full_data_x})
    if i % 10 == 0 or i == 1:
        print("Step %i, Avg Distance: %f" % (i, d))

Step 1, Avg Distance: 0.341471
Step 10, Avg Distance: 0.221609
Step 20, Avg Distance: 0.220328
Step 30, Avg Distance: 0.219776
Step 40, Avg Distance: 0.219419
Step 50, Avg Distance: 0.219154
Step 60, Avg Distance: 0.218940
Step 70, Avg Distance: 0.218764
Step 80, Avg Distance: 0.218614
Step 90, Avg Distance: 0.218484
Step 100, Avg Distance: 0.218373


In [11]:
# Assign a label to each centroid
# Count total number of labels per centroid, 
# using the label of each training
# sample to their closest centroid (given by 'idx')
counts = np.zeros(shape=(k, num_classes))

for i in range(len(idx)):
    counts[idx[i]] += mnist.train.labels[i]

# Assign the most frequent label to the centroid
labels_map = [np.argmax(c) for c in counts]
labels_map = tf.convert_to_tensor(labels_map)

# Evaluation ops
# Lookup: centroid_id -> label
cluster_label = tf.nn.embedding_lookup(labels_map, cluster_idx)

# Compute accuracy
correct_prediction = tf.equal(cluster_label, 
                              tf.cast(tf.argmax(Y, 1), tf.int32))
accuracy_op = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

# Test Model
test_x, test_y = mnist.test.images, mnist.test.labels
print("Test Accuracy:", sess.run(accuracy_op, 
                                 feed_dict={X: test_x, Y: test_y}))

Test Accuracy: 0.7273


### tf.nn.embedding_lookup 

참고자료 : https://code.i-harness.com/ko/q/2141556

embedding_lookup 함수는 params 텐서의 행을 검색합니다. 이 동작은 배열에 numpy로 인덱스를 사용하는 것과 비슷합니다. 예 :

In [42]:
matrix = np.eye(4)  # 64-dimensional embeddings
ids = np.array([0, 2])
print( matrix[ids] )  # prints a matrix of shape [4, 64] 

[[ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]]


다음은 간단하게 텐서플로우로 작성한 것입니다.

In [34]:
params = tf.constant([10, 20, 30, 40])
ids = tf.constant([0,1,2,1])
print( tf.nn.embedding_lookup(params, ids).eval(session=sess) )

[10 20 30 20]
